"""Render mtg.toml + sing-box.json on the RU box from seed + current descriptor."""
from __future__ import annotations

import hashlib
import json


class ConfigError(RuntimeError):
    pass


def _derive_mtg_secret(seed) -> str:
    """Deterministic 16-byte secret derived from reality_uuid.
    mtg's Fake-TLS secret format: lowercase hex of 16 bytes.
    """
    h = hashlib.sha256(seed.reality_uuid.encode()).digest()[:16]
    return h.hex()


def render_mtg_config(seed, *, sing_box_socks_port: int) -> bytes:
    """Render mtg.toml. mtg listens on 0.0.0.0:443; upstream is captured
    by iptables and redirected into sing-box (so mtg's hardcoded Telegram
    upstream is fine — the redirect intercepts before connect)."""
    secret = _derive_mtg_secret(seed)
    text = f"""# Generated by mthydra.ru_agent.config_gen — do not edit.
debug = false
bind-to = "0.0.0.0:443"
secret = "{secret}"

[network]
prefer-ip = "prefer-ipv4"

# Fake-TLS cover SNI presented to clients connecting to this RU box.
domain-fronting = "{seed.sni}"
"""
    return text.encode("utf-8")


def render_sing_box_config(
    seed, descriptor_payload: dict, *, tproxy_port: int,
) -> bytes:
    """Render sing-box client config.

    - inbound: tproxy on 127.0.0.1:<tproxy_port>
    - outbounds: one Reality outbound per exit + a selector that random-picks
    - selector strategy 'random' for per-connection spread (E-D9)
    """
    exits = descriptor_payload.get("exits", [])
    if not exits:
        raise ConfigError("descriptor contains no exits")

    vless_outbounds = []
    for exit in exits:
        host, port = exit["endpoint"].rsplit(":", 1)
        vless_outbounds.append({
            "type": "vless",
            "tag": f"exit-{exit['fingerprint']}",
            "server": host,
            "server_port": int(port),
            "uuid": seed.reality_uuid,
            "flow": "xtls-rprx-vision",
            "tls": {
                "enabled": True,
                "server_name": exit["cover_sni"],
                "reality": {
                    "enabled": True,
                    "public_key": exit["reality_pubkey"],
                    "short_id": "",
                },
            },
        })

    selector = {
        "type": "selector",
        "tag": "to-eu-exits",
        "outbounds": [o["tag"] for o in vless_outbounds],
        "default": vless_outbounds[0]["tag"],
        "interrupt_exist_connections": False,
    }

    payload = {
        "log": {"level": "warn", "timestamp": True},
        "inbounds": [
            {
                "type": "tproxy",
                "tag": "tproxy-in",
                "listen": "127.0.0.1",
                "listen_port": tproxy_port,
                "network": "tcp",
                "sniff": False,
            }
        ],
        "outbounds": [
            *vless_outbounds,
            selector,
            {"type": "direct", "tag": "direct"},
        ],
        "route": {
            "rules": [],
            "final": "to-eu-exits",
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")
