"""Render mtg.toml + sing-box.json on the RU box from seed + current descriptor."""
from __future__ import annotations

import json

from mthydra import proxy_link


class ConfigError(RuntimeError):
    pass


def render_mtg_config(seed, *, sing_box_socks_port: int) -> bytes:
    """Render mtg.toml. mtg listens on 0.0.0.0:443; upstream is captured
    by iptables and redirected into sing-box (so mtg's hardcoded Telegram
    upstream is fine — the redirect intercepts before connect)."""
    secret = proxy_link.derive_mtg_secret(seed.reality_uuid, seed.sni)
    text = f"""# Generated by mthydra.ru_agent.config_gen — do not edit.
debug = false
bind-to = "0.0.0.0:443"
secret = "{secret}"

[network]
prefer-ip = "prefer-ipv4"

# Fake-TLS cover SNI presented to clients connecting to this RU box.
domain-fronting = "{seed.sni}"
"""
    return text.encode("utf-8")


def render_sing_box_config(
    seed, descriptor_payload: dict, *, tproxy_port: int,
) -> bytes:
    """Render sing-box client config.

    - inbound: tproxy on 127.0.0.1:<tproxy_port>
    - outbounds: one Reality outbound per exit + a selector that random-picks
    - selector strategy 'random' for per-connection spread (E-D9)
    """
    # The controller signs this key as "eu_exit_set" (descriptor.payload
    # canonical_bytes); reading "exits" silently saw zero exits on every box.
    exits = descriptor_payload.get("eu_exit_set", [])
    if not exits:
        raise ConfigError("descriptor contains no exits")

    vless_outbounds = []
    for exit in exits:
        host, port = exit["endpoint"].rsplit(":", 1)
        vless_outbounds.append({
            "type": "vless",
            "tag": f"exit-{exit['fingerprint']}",
            "server": host,
            "server_port": int(port),
            "uuid": seed.reality_uuid,
            "flow": "xtls-rprx-vision",
            "tls": {
                "enabled": True,
                "server_name": exit["cover_sni"],
                # sing-box's Reality *client* requires uTLS; without it sing-box
                # exits with "uTLS is required by reality client".
                "utls": {"enabled": True, "fingerprint": "chrome"},
                "reality": {
                    "enabled": True,
                    "public_key": exit["reality_pubkey"],
                    "short_id": "",
                },
            },
        })

    selector = {
        "type": "selector",
        "tag": "to-eu-exits",
        "outbounds": [o["tag"] for o in vless_outbounds],
        "default": vless_outbounds[0]["tag"],
        "interrupt_exist_connections": False,
    }

    payload = {
        "log": {"level": "warn", "timestamp": True},
        "inbounds": [
            {
                # 'redirect' (not 'tproxy'): mtg's traffic is locally generated,
                # captured via nat/REDIRECT in OUTPUT (TPROXY is PREROUTING-only).
                "type": "redirect",
                "tag": "redirect-in",
                "listen": "127.0.0.1",
                "listen_port": tproxy_port,
                # sing-box 1.13 'redirect' inbound has no 'network'/'sniff'
                # fields (sniff moved to route actions); listing them is a
                # hard parse error.
            }
        ],
        "outbounds": [
            *vless_outbounds,
            selector,
            {"type": "direct", "tag": "direct"},
        ],
        "route": {
            "rules": [],
            "final": "to-eu-exits",
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")
